# My aliases

alias l='ls'
alias ll='ls -l'
alias l.='ls -A'
alias ll.='ls -al'
alias du1='du -h --max-depth=1'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias e='vim'
alias grep='grep --color=auto'
alias pgrep='pgrep -l'
alias rmbaks='find . -name "*~" -exec rm {} \;'
alias tea='echo "notify-send -i dialog-information -t 0 \"Tea!\" \"Your tea is nicely brewed\"" | at now +4 minutes'
alias screenx='screenx.sh && exit'
