# My aliases

alias realias='vim ~/.bash_aliases; source ~/.bash_aliases'
alias l='ls'
alias ll='ls -l'
alias l.='ls -A'
alias ll.='ls -al'
alias lsa='ls -ls .*'
alias lsd='ls -ld *(-/DN)'
alias du1='du -hs *(/)'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias e='vim'
alias grep='grep --color=auto'
alias pgrep='pgrep -l'
alias rmbaks='find . -name "*~" -exec rm {} \;'
alias tea='echo "notify-send -i gtk-dialog-info -t0 \"Tea is brewed\"" | at now + 4 minutes'
alias elog='tail -n50 -f /var/log/apache2/error_log'
alias screenx='screenx.sh && exit'
